### PR TITLE
Some optimizations

### PR DESCRIPTION
**Pull request by budgetdevv**
Welp

### CODE REVIEW

**Review by JustAeris — CHANGES_REQUESTED** [review]
`bin` and `obj` must be removed before merging!

**Comment by DelightedCat** [comment]
To join in on the discussion, it seems like the `.idea` directory wasn't added to the `.gitignore` yet either.

**Comment by AlmightyLks** [comment]
@JustAeris 
Add a .gitignore file.
Temporary and unnecessary project folders such as `.vs`, `.idea`, `bin` & `obj` are not something one removes by hand on every commit.

**Comment by budgetdevv** [comment]
I somehow assumed that a .gitignore was added...seems like a thing people do upon their first commit

**Comment by budgetdevv** [comment]
Will add the relevant .gitignore

**Comment by budgetdevv** [comment]
Might wanna check if it works first before merging!

**Review by AraHaan — CHANGES_REQUESTED** [review]
delet the files maked with delet but could not mark the dll's, pdbs, a few other non-text files.

**Comment by budgetdevv** [comment]
Apparently I had to remove those folders manually

**Comment by budgetdevv** [comment]
https://i.gyazo.com/c4b5354b32ad1bc08cfd153983556bfd.png

**Comment by budgetdevv** [comment]
Might want to fix typo in project desc...

**Review by JustAeris — APPROVED** [review]
All good!

**Pull request merged**
